### ISSUE TITLE
Does this get updated?

### ISSUE THREAD

**Issue by nsauter** [mochikun/EDID_checksum#1]
Im currently writing a python script to generate my own edid blob with modeline input. I have my problems with the edid checksum right now ( I guess im just too bad at programming) and i was hoping your tool can help but as it seems iw wont work with the input of my edid.bin data

**Comment by mochikun** [comment]
This script was for python2. I updated to work python3. Please try to use latest code.

**Comment by nsauter** [comment]
Is there a way to do this without opening the written file by just giving
the method a list?

Besides that im not able to calculate my checksum with the script. Error:

Traceback (most recent call last):
  File "./checksum.py", line 20, in <module>
    csum = unpack('B',f.read(1))[0]
struct.error: unpack requires a bytes object of length 1

**Comment by mochikun** [comment]
I think your edid binary file size < 128 Bytes. This script expects input file size >= 128 Bytes.
I added file size check method and changed expected input size >= 127 Bytes.

**Comment by mochikun** [comment]
I'll close this issue.

**Comment by mochikun** [comment]
I'll close this issue.
